token: 
  expiration_time: 86400000
  secret: '{cipher}AQBRCDxXrxcD3iexB6mS+1kVZgGXd8MZSoz/cQii8944wwKklUQzSzeQIOEaDTFXCagOSyTzIU5bFEkKFoDoXQZ+3nijvuIjP9CBiCCjBG5j4r9JHsmLTXJS0raRakfv3N6G4dZc7DjPJJj78hp66zj5Ac7cxoQ69PUK+e7GDmFSaHCvqeodTvxrDEV20wRhC6V3AdZpe9ihrTlPKEjj2M6klS/tRnHE0gPvIobhY0ACVZx/rfnlQqR1ELgIQeQoM2gwjSVk+2iWlk3/2lJW9J4K+xDTcXfEd9euXK6cPmmppMIzxeircbhGS0UJn+eczCRrtOUUSCqh701ShZ5obwn/z/Lc6RkXkQa4aFED8YmxVwN0LZIMCpxz3Ha619Mk8Pc=' 

gateway:
  ip: 182.225.15.66

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQCxrHO8EGMQxj4M1mL+lVV5l9wOYGlC+KlRV9hyWNr2e+QQvE0MbAZlRcFaIfp+ngQ9K1vHwgcZ0F+Z02Y2hyZZ9bSPVVpjhyIIDLxiujClIR0RXLRFEVt8Cz/dmV3I6yWQovk0t99qEl7jfJ01t8x+Lnuvs4gSqaG/W0rQe/Gk+vdOKF1ZAmmZ/BaNXWFfvcqXD5KfS2Q0PBQnKHQjSo2CFMpTOcEjfwKC6ItGZZqqA32hWRv5XGcys4Q27b8JkY8pVTdd7XaLpa86Kedv+YD8l+XtblyP015p+mXXR8bZWoAMZ58K5louQxaPMczT8KivVRTCsbTroUFSnAtXZBzyOS3+MO4ipGU1QeIgnOS5iDXoii1VlAlKvrGQq8wfYIo='